question_data = [
    {
            "type": "boolean",
            "difficulty": "medium",
            "category": "Geography",
            "question": "Norway has a larger land area than Sweden.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "type": "boolean",
            "difficulty": "medium",
            "category": "Geography",
            "question": "Seoul is the capital of North Korea.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "type": "boolean",
            "difficulty": "medium",
            "category": "Geography",
            "question": "The surface area of Russia is slightly larger than that of the dwarf planet Pluto.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "type": "boolean",
            "difficulty": "medium",
            "category": "Geography",
            "question": "Italy and Ireland are the only countries in Europe that start with the letter I.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "type": "boolean",
            "difficulty": "medium",
            "category": "Geography",
            "question": "Israel is 7 hours ahead of New York.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "type": "boolean",
            "difficulty": "medium",
            "category": "Geography",
            "question": "Route 66 in the United States spans the entire mainland of America, from California to New York.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "type": "boolean",
            "difficulty": "medium",
            "category": "Geography",
            "question": "The Sonoran Desert is located in eastern Africa.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "type": "boolean",
            "difficulty": "medium",
            "category": "Geography",
            "question": "The capital of the US State Ohio is the city of Chillicothe.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "type": "boolean",
            "difficulty": "medium",
            "category": "Geography",
            "question": "&quot;Mongolia&quot; was a part of the now non-existent U.S.S.R.",
            "correct_answer": "False",
            "incorrect_answers": ["True"],
        },
        {
            "type": "boolean",
            "difficulty": "medium",
            "category": "Geography",
            "question": "The longest place named in the United States is Lake Chargoggagoggmanchauggagoggchaubunagungamaugg, located near Webster, MA.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
]
